version: "3.1"
services:
  nodejs-server:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 7070:7070

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: pg-db-test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
    ports:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080